// Generate web/.env from the root env.env (single source of truth for secrets).
// Next.js and Prisma read web/.env; we never duplicate secrets by hand.
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseEnvFile, buildDatabaseUrl } from "./read-env.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../.env"); // web/.env

const env = parseEnvFile();
const { url, dbName } = buildDatabaseUrl(env);

const lines = [
  "# Generated by scripts/sync-env.mjs from ../env.env — do not edit by hand.",
  `DATABASE_URL="${url}"`,
  "",
  `SN_INSTANCE_URL="${env.SN_INSTANCE_URL ?? ""}"`,
  `SN_USER="${env.SN_USER ?? env.SN_USERNAME ?? ""}"`,
  `SN_PASSWORD="${env.SN_PASSWORD ?? ""}"`,
  "",
  `AZURE_OPENAI_ENDPOINT="${env.AZURE_OPENAI_ENDPOINT ?? ""}"`,
  `AZURE_OPENAI_KEY="${env.AZURE_OPENAI_KEY ?? ""}"`,
  `AZURE_OPENAI_DEPLOYMENT="${env.AZURE_OPENAI_DEPLOYMENT ?? "gpt-4o-mini"}"`,
  `AZURE_OPENAI_VERSION="${env.AZURE_OPENAI_VERSION ?? "2025-01-01-preview"}"`,
  "",
  `# Operator login. "true" requires every operator to sign in at /login (create an admin first:`,
  `#   npx tsx scripts/auth-user.ts create <email> global_admin). Leave blank to keep the app open.`,
  `AUTH_ENABLED="${env.AUTH_ENABLED ?? ""}"`,
  "",
  `# Microsoft 365 single sign-on (Entra app registration). Set all three to enable the SSO button.`,
  `# Register the redirect URI <origin>/api/auth/sso/callback in the app. AUTH_PUBLIC_ORIGIN forces`,
  `# that origin behind a tunnel/proxy (cloudflared/ngrok) — set it to the URL you sign in through.`,
  `AUTH_PUBLIC_ORIGIN="${env.AUTH_PUBLIC_ORIGIN ?? ""}"`,
  `AZURE_SSO_TENANT_ID="${env.AZURE_SSO_TENANT_ID ?? ""}"`,
  `AZURE_SSO_CLIENT_ID="${env.AZURE_SSO_CLIENT_ID ?? ""}"`,
  `AZURE_SSO_CLIENT_SECRET="${env.AZURE_SSO_CLIENT_SECRET ?? ""}"`,
  "",
];

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT}`);
console.log(`  DATABASE_URL -> ${env.POSTGRES_HOST}:${env.POSTGRES_PORT}/${dbName}`);
console.log(`  SN_INSTANCE_URL -> ${env.SN_INSTANCE_URL ?? "(missing)"}`);
