#Requires -Version 7.0

# Coretelligent.GoogleWorkspace
# Google Workspace user lifecycle via the Admin SDK Directory API. Onboard creates a user,
# places them in an OU (never Root) and adds group memberships; offboard captures evidence,
# removes groups, moves to the Inactive OU and SUSPENDS (never deletes — the `archive` module
# handles deletion later). Idempotent: checks state before changing it.
#
# Auth: domain-wide-delegated service account. Secret `google-admin` -> a bearer access token
# (Username/Password carry the OAuth client; Fields.CustomerId is the Google customer id).

Set-StrictMode -Version Latest

$script:GoogleApiUrl = 'https://admin.googleapis.com/admin/directory/v1'
$script:GoogleToken  = $null

function Get-CtgProp {
    param($Object, [Parameter(Mandatory)][string]$Name)
    if ($null -eq $Object) { return $null }
    if ($Object -is [hashtable]) { return $Object[$Name] }
    $p = $Object.PSObject.Properties[$Name]
    if ($p) { return $p.Value }
    return $null
}

function Connect-CtgGoogle {
    <#
    .SYNOPSIS
        Establish a Directory API session. In production this exchanges the delegated
        service-account credential for a short-lived OAuth2 access token; the runner brokers
        the credential reference from the app and resolves it via Coretelligent.Secrets.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][pscredential]$Credential,
        [string]$CustomerId = 'my_customer'
    )
    # The OAuth2 service-account JWT assertion flow lives in the production credential resolver;
    # here we record the token carried on the resolved secret so Invoke-CtgGoogleApi can authenticate.
    $script:GoogleToken    = ConvertFrom-SecureString $Credential.Password -AsPlainText
    $script:GoogleCustomer = $CustomerId
    Write-Verbose "Google Workspace session established."
}

function Invoke-CtgGoogleApi {
    # Single HTTP seam (bearer auth). Mocked in tests. Returns $null on 404 (not found).
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Method, [Parameter(Mandatory)][string]$Path, $Body)
    if (-not $script:GoogleToken) { throw "Call Connect-CtgGoogle first." }
    $p = @{
        Method      = $Method
        Uri         = "$script:GoogleApiUrl$Path"
        Headers     = @{ Authorization = "Bearer $script:GoogleToken" }
        ContentType = 'application/json'
    }
    if ($Body) { $p.Body = ($Body | ConvertTo-Json -Depth 8) }
    try { return Invoke-RestMethod @p }
    catch {
        if ($_.Exception.Response.StatusCode.value__ -eq 404) { return $null }
        throw
    }
}

function Get-CtgGoogleUser {
    param([Parameter(Mandatory)][string]$Email)
    Invoke-CtgGoogleApi -Method GET -Path "/users/$Email"
}

function Get-CtgGoogleUserGroups {
    # Group emails the user currently belongs to (empty array if none).
    param([Parameter(Mandatory)][string]$Email)
    $resp = Invoke-CtgGoogleApi -Method GET -Path "/groups?userKey=$Email"
    $groups = Get-CtgProp $resp 'groups'
    if (-not $groups) { return @() }
    @($groups | ForEach-Object { Get-CtgProp $_ 'email' })
}

function Invoke-CtgGoogleOnboarding {
    <#
    .SYNOPSIS
        Idempotently create a Google user, place them in the target OU (never Root) and add
        group memberships. Config: ou, groups[], password{mode,sharedSecret}.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory)][pscustomobject]$User,
        [Parameter(Mandatory)][pscustomobject]$Config,
        # Generated by the runner (New-CtgCompliantPassword lives in Coretelligent.M365) and passed
        # in, mirroring Invoke-CtgM365Onboarding — the module never reaches into another module.
        [Parameter(Mandatory)][securestring]$InitialPassword
    )

    $actions = [System.Collections.Generic.List[string]]::new()
    $email = $User.UserPrincipalName
    $ou = (Get-CtgProp $Config 'ou') ?? '/Active Users'
    if ($ou -eq '/' -or $ou -eq '') { throw "refusing to place $email in the Root OU" }

    if (Get-CtgGoogleUser -Email $email) {
        $actions.Add("Google user already exists: $email")
    }
    elseif ($PSCmdlet.ShouldProcess($email, "Create Google user in $ou")) {
        $body = @{
            primaryEmail = $email
            name         = @{ givenName = $User.FirstName; familyName = $User.LastName }
            password     = (ConvertFrom-SecureString $InitialPassword -AsPlainText)
            orgUnitPath  = $ou
            changePasswordAtNextLogin = $true
        }
        Invoke-CtgGoogleApi -Method POST -Path '/users' -Body $body | Out-Null
        $actions.Add("created Google user: $email in $ou")
    }

    # Ensure OU (a pre-existing user may sit elsewhere) — idempotent.
    if ($PSCmdlet.ShouldProcess($email, "Ensure OU $ou")) {
        Invoke-CtgGoogleApi -Method PUT -Path "/users/$email" -Body @{ orgUnitPath = $ou } | Out-Null
    }

    # Add to groups (skip groups the user is already in).
    $current = Get-CtgGoogleUserGroups -Email $email
    foreach ($g in @((Get-CtgProp $Config 'groups'))) {
        if (-not $g) { continue }
        if ($current -contains $g) { $actions.Add("already in group: $g"); continue }
        if ($PSCmdlet.ShouldProcess($email, "Add to group $g")) {
            Invoke-CtgGoogleApi -Method POST -Path "/groups/$g/members" -Body @{ email = $email; role = 'MEMBER' } | Out-Null
            $actions.Add("added to group: $g")
        }
    }

    [pscustomobject]@{ System = 'google-workspace'; Status = 'ok'; Email = $email; Ou = $ou; Actions = $actions.ToArray() }
}

function Invoke-CtgGoogleOffboarding {
    <#
    .SYNOPSIS
        Capture evidence, remove groups, move to the Inactive OU and SUSPEND the user. NEVER
        deletes (guardrail do-not-delete). Config: inactiveOu, transferTarget, guardrails[].
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param([Parameter(Mandatory)][pscustomobject]$User, [Parameter(Mandatory)][pscustomobject]$Config)

    $actions = [System.Collections.Generic.List[string]]::new()
    $email = $User.UserPrincipalName

    if (-not (Get-CtgGoogleUser -Email $email)) {
        return [pscustomobject]@{ System = 'google-workspace'; Status = 'ok'; Email = $email; Actions = @("Google user not found ($email)"); Evidence = @{ Groups = @() } }
    }

    # 1. Evidence FIRST — snapshot group memberships before we remove anything. @() keeps it an
    # array even for a single group (PowerShell unrolls one-element returns), so .Count is safe.
    $groupEvidence = @(Get-CtgGoogleUserGroups -Email $email)
    $actions.Add("captured $($groupEvidence.Count) group membership(s) as evidence")

    # 2. Remove group memberships.
    foreach ($g in $groupEvidence) {
        if ($PSCmdlet.ShouldProcess($email, "Remove from group $g")) {
            Invoke-CtgGoogleApi -Method DELETE -Path "/groups/$g/members/$email" | Out-Null
            $actions.Add("removed from group: $g")
        }
    }

    # 3. Move to the Inactive OU (must precede any Drive transfer).
    $inactiveOu = (Get-CtgProp $Config 'inactiveOu') ?? '/Email & Calendar/Inactive'
    if ($PSCmdlet.ShouldProcess($email, "Move to $inactiveOu")) {
        Invoke-CtgGoogleApi -Method PUT -Path "/users/$email" -Body @{ orgUnitPath = $inactiveOu } | Out-Null
        $actions.Add("moved to OU: $inactiveOu")
    }

    # 4. On request: transfer Drive ownership to the delegate (only valid once moved out of Active Users).
    $transfer = Get-CtgProp $Config 'transferTarget'
    if ($transfer -and $PSCmdlet.ShouldProcess($email, "Transfer Drive to $transfer")) {
        Invoke-CtgGoogleApi -Method POST -Path '/dataTransfer' -Body @{ oldOwnerUserId = $email; newOwnerUserId = $transfer } | Out-Null
        $actions.Add("transferred Drive ownership to: $transfer")
    }

    # 5. Suspend (deactivate) — NEVER delete.
    if ($PSCmdlet.ShouldProcess($email, "Suspend Google user")) {
        Invoke-CtgGoogleApi -Method PUT -Path "/users/$email" -Body @{ suspended = $true } | Out-Null
        $actions.Add("suspended Google user: $email")
    }

    [pscustomobject]@{
        System   = 'google-workspace'
        Status   = 'ok'
        Email    = $email
        Evidence = @{ Groups = @($groupEvidence) }
        Actions  = $actions.ToArray()
    }
}

function Confirm-CtgGoogle {
    <#
    .SYNOPSIS
        Post-action read-back. No mutations; returns { ok; checks[] }.
        onboard -> user present, not suspended, in a non-Root OU.
        offboard -> user suspended and moved out of the Active Users OU.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][pscustomobject]$User,
        [Parameter(Mandatory)][pscustomobject]$Config,
        [Parameter(Mandatory)][ValidateSet('onboard', 'offboard')][string]$Action
    )
    $email = $User.UserPrincipalName
    $u = Get-CtgGoogleUser -Email $email
    $ou = if ($u) { Get-CtgProp $u 'orgUnitPath' } else { $null }
    $suspended = [bool](Get-CtgProp $u 'suspended')
    $checks = [System.Collections.Generic.List[hashtable]]::new()

    if ($Action -eq 'onboard') {
        $checks.Add(@{ name = 'Google user present'; expected = $true; actual = [bool]$u; pass = [bool]$u })
        $checks.Add(@{ name = 'not in Root OU'; expected = $true; actual = ($ou -and $ou -ne '/'); pass = [bool]($ou -and $ou -ne '/') })
    }
    else {
        $checks.Add(@{ name = 'Google user suspended (not deleted)'; expected = $true; actual = $suspended; pass = $suspended })
        $inactiveOu = (Get-CtgProp $Config 'inactiveOu') ?? '/Email & Calendar/Inactive'
        $moved = ($ou -eq $inactiveOu)
        $checks.Add(@{ name = "moved to $inactiveOu"; expected = $true; actual = $moved; pass = $moved })
    }
    $ok = -not ($checks | Where-Object { -not $_.pass })
    [pscustomobject]@{ ok = [bool]$ok; checks = @($checks) }
}

Export-ModuleMember -Function Connect-CtgGoogle, Invoke-CtgGoogleApi, Get-CtgGoogleUser, Get-CtgGoogleUserGroups, Invoke-CtgGoogleOnboarding, Invoke-CtgGoogleOffboarding, Confirm-CtgGoogle
