#Requires -Version 7.0

# Coretelligent.Slack
# Slack user lifecycle via the SCIM API. Onboard invites/creates the member; offboard DEACTIVATES.
# Idempotent: always looks the user up by email first, so a re-run after a partial failure is safe.
#
# Auth: an OAuth token with the `admin` scope. Secret `slack` -> { Token } (synonyms below).
#   Base: https://api.slack.com/scim/v2   Header: Authorization: Bearer <token>
# The token must be generated by a Slack Owner/Admin, and SCIM needs a Business+ (or Enterprise
# Grid) plan. On a plan without SCIM every call answers 404/403 — which we report as exactly that,
# because "your plan doesn't include the API" is the single most likely reason this won't work and
# it is indistinguishable from a bad token unless we say so.
#
# DEACTIVATE, NOT DELETE. In SCIM, `DELETE /Users/{id}` on Slack deactivates the account — it does
# not destroy it. That is the desired offboard behaviour (messages and files are retained, which is
# what a leaver's data is usually needed for), and it is reversible from the admin console.

Set-StrictMode -Version Latest

$script:SlackScimUrl = 'https://api.slack.com/scim/v2'
$script:SlackToken   = $null

function Get-CtgProp {
    param($Object, [Parameter(Mandatory)][string]$Name)
    if ($null -eq $Object) { return $null }
    if ($Object -is [System.Collections.IDictionary]) { return $Object[$Name] }
    $p = $Object.PSObject.Properties[$Name]
    if ($p) { return $p.Value }
    return $null
}

function Connect-CtgSlack {
    <#
    .SYNOPSIS
        Point the module at a Slack SCIM token. A pure local assignment — no network call — so each
        job re-reads the brokered secret and a rotated token applies on the very next job.
    #>
    param(
        [Parameter(Mandatory)][string]$Token,
        [string]$BaseUrl
    )
    if ($BaseUrl) { $script:SlackScimUrl = $BaseUrl.TrimEnd('/') }
    $script:SlackToken = $Token
}

function Invoke-CtgSlackScim {
    # The single HTTP seam (mocked in tests). Everything else in this module goes through here.
    param(
        [Parameter(Mandatory)][ValidateSet('GET', 'POST', 'PATCH', 'DELETE')][string]$Method,
        [Parameter(Mandatory)][string]$Path,
        $Body,
        [hashtable]$Query
    )
    if (-not $script:SlackToken) { throw "Call Connect-CtgSlack first." }

    $uri = "$($script:SlackScimUrl)$Path"
    if ($Query -and $Query.Count) {
        $pairs = foreach ($k in $Query.Keys) { "$([uri]::EscapeDataString($k))=$([uri]::EscapeDataString([string]$Query[$k]))" }
        $uri = "$uri`?$($pairs -join '&')"
    }
    # NOT $args — that is a reserved automatic variable, and assigning to it under StrictMode is a trap
    # the unit tests would never catch (they mock this seam, so this body only ever runs for real).
    $req = @{
        Method      = $Method
        Uri         = $uri
        Headers     = @{ Authorization = "Bearer $($script:SlackToken)"; Accept = 'application/json' }
        ErrorAction = 'Stop'
    }
    if ($null -ne $Body) {
        $req.Body        = ($Body | ConvertTo-Json -Depth 10 -Compress)
        $req.ContentType = 'application/json'
    }
    Invoke-RestMethod @req
}

function Test-CtgSlackNoScim {
    # Slack answers 404 (and sometimes 403) for the whole SCIM surface on a plan that doesn't include
    # it. Told apart from a bad token so the operator isn't sent to rotate a credential that is fine.
    param([string]$Message)
    return ([string]$Message -match 'HTTP 404|\b404\b|not_found|plan|upgrade')
}

function Find-CtgSlackUser {
    <#
    .SYNOPSIS
        Find a Slack member by email. Returns the SCIM user object, or $null when there is no match.
    .DESCRIPTION
        Email is the only reliable key: Slack usernames are display handles that collide and change.
        The SCIM filter is `userName eq "x"` OR `emails.value eq "x"` depending on how the workspace
        provisions; Slack matches on email for both, and we query the email attribute explicitly.

        A deactivated member STILL MATCHES (with active=false) — that's deliberate: onboarding must be
        able to tell "no such person" from "a returning leaver whose account is switched off", which
        are opposite actions.
    #>
    # AllowEmptyString so an empty UPN reaches the guard below and gets the ACTIONABLE message ("fix the
    # address on the case") instead of PowerShell's opaque "cannot bind argument ... empty string",
    # which tells an operator nothing about where the bad data actually came from.
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Email)

    # Validate the SHAPE before it becomes part of a filter expression. The address originates in a
    # ServiceNow form field, so it is not ours to trust: escaping alone is the wrong last line of
    # defence (a trailing backslash would escape the closing quote and leave the filter unterminated),
    # and an EMPTY value is worse than a malformed one — `email eq ""` matches nobody, so onboarding
    # would sail past the "already exists?" check and create a Slack account with a blank username.
    # An address that cannot be an address is a bad intake record, not something to go querying with.
    if ($Email -notmatch '^[^@\s"\\]+@[^@\s"\\]+\.[^@\s"\\]+$') {
        throw "'$Email' is not a usable email address — Slack members are matched by email. Fix the address on the case (this comes from the ServiceNow intake)."
    }
    $resp = Invoke-CtgSlackScim -Method GET -Path '/Users' -Query @{ filter = "email eq ""$Email"""; count = 1 }
    $resources = Get-CtgProp $resp 'Resources'
    if ($null -eq $resources) { return $null }
    $first = @($resources)[0]
    if (-not $first) { return $null }
    return $first
}

function Test-CtgSlackActive {
    # SCIM `active` — Slack returns a real boolean, but be liberal: some responses stringify it.
    param($User)
    $a = Get-CtgProp $User 'active'
    if ($null -eq $a) { return $false }
    if ($a -is [bool]) { return $a }
    return ([string]$a -match '^(true|1)$')
}

function Invoke-CtgSlackOnboarding {
    <#
    .SYNOPSIS
        Ensure the user has an ACTIVE Slack account. Idempotent.
    .DESCRIPTION
        check -> confirm -> create/reactivate, the same shape every account-creating module here uses:
          already active            -> no-op (the common re-run case)
          exists but DEACTIVATED    -> reactivate (PATCH active=true) rather than create a duplicate,
                                       which is what a returning employee looks like
          absent                    -> create (SCIM POST), which sends Slack's invite
        Creating a second account for someone who already has one is the failure this ordering exists
        to prevent: Slack would accept it, and the person would end up with two identities.
    #>
    param(
        [Parameter(Mandatory)][pscustomobject]$User,
        [Parameter(Mandatory)][pscustomobject]$Config
    )
    $actions = [System.Collections.Generic.List[string]]::new()
    $email   = $User.UserPrincipalName

    $existing = $null
    try { $existing = Find-CtgSlackUser -Email $email }
    catch {
        $m = [string]$_.Exception.Message
        if (Test-CtgSlackNoScim $m) { throw "Slack SCIM is not available for this workspace ($m). SCIM needs a Business+ or Enterprise Grid plan, and a token with the 'admin' scope generated by an Owner/Admin. See /help/slack." }
        throw
    }

    if ($existing) {
        if (Test-CtgSlackActive $existing) {
            $actions.Add("$email already has an active Slack account — nothing to do")
            return [pscustomobject]@{ System = 'slack'; Status = 'ok'; Email = $email; Actions = $actions.ToArray() }
        }
        # A DEACTIVATED account for this exact email: reactivate rather than create a second identity.
        $id = Get-CtgProp $existing 'id'
        Invoke-CtgSlackScim -Method PATCH -Path "/Users/$id" -Body @{
            schemas    = @('urn:ietf:params:scim:api:messages:2.0:PatchOp')
            Operations = @(@{ op = 'replace'; path = 'active'; value = $true })
        } | Out-Null
        $actions.Add("reactivated $email's existing (deactivated) Slack account — a returning member keeps their history")
        return [pscustomobject]@{ System = 'slack'; Status = 'ok'; Email = $email; Actions = $actions.ToArray() }
    }

    $displayName = if ($User.PSObject.Properties['DisplayName'] -and $User.DisplayName) { [string]$User.DisplayName } else { $email }
    $body = @{
        schemas   = @('urn:ietf:params:scim:schemas:core:2.0:User')
        userName  = $email
        displayName = $displayName
        emails    = @(@{ value = $email; primary = $true })
        active    = $true
    }
    $created = Invoke-CtgSlackScim -Method POST -Path '/Users' -Body $body
    $newId = Get-CtgProp $created 'id'
    $actions.Add("created a Slack account for $email$(if ($newId) { " (id $newId)" }) — Slack sends the invite")
    [pscustomobject]@{ System = 'slack'; Status = 'ok'; Email = $email; Actions = $actions.ToArray() }
}

function Invoke-CtgSlackOffboarding {
    <#
    .SYNOPSIS
        Deactivate the leaver's Slack account. Idempotent, and never destructive.
    .DESCRIPTION
        SCIM DELETE on Slack DEACTIVATES — it does not erase the member or their messages. That is
        what we want on an offboard: the account can no longer sign in, the seat is freed, and the
        content is retained for whoever inherits the work.

        A user who isn't in Slack at all, or is already deactivated, is reported honestly as a no-op
        rather than as a failure: a leaver who never had Slack is a perfectly normal case, and failing
        the step would block the rest of the offboard for no reason.
    #>
    param(
        [Parameter(Mandatory)][pscustomobject]$User,
        [Parameter(Mandatory)][pscustomobject]$Config
    )
    $actions = [System.Collections.Generic.List[string]]::new()
    # StrictMode-safe identity read: an offboard payload may carry no UserPrincipalName property at all
    # (a ServiceNow UM intake carries `userToOffboard`), and a dot-read of an absent property throws.
    # Slack is looked up by email (users.lookupByEmail) — a bare display name would report a false
    # "not found" success on an offboard, so no email is an error, not a silent no-op.
    $email   = [string](@('UserPrincipalName', 'email', 'WorkEmail', 'userToOffboard') | ForEach-Object { Get-CtgProp $User $_ } | Where-Object { $_ -match '@' } | Select-Object -First 1)
    if (-not $email) { throw "slack: the case carries no email/UPN for the user to offboard — set the user's email on the case and re-run." }

    $existing = $null
    try { $existing = Find-CtgSlackUser -Email $email }
    catch {
        $m = [string]$_.Exception.Message
        if (Test-CtgSlackNoScim $m) { throw "Slack SCIM is not available for this workspace ($m). SCIM needs a Business+ or Enterprise Grid plan, and a token with the 'admin' scope generated by an Owner/Admin. See /help/slack." }
        throw
    }

    if (-not $existing) {
        $actions.Add("$email has no Slack account — nothing to deactivate")
        return [pscustomobject]@{ System = 'slack'; Status = 'ok'; Email = $email; Actions = $actions.ToArray() }
    }
    if (-not (Test-CtgSlackActive $existing)) {
        $actions.Add("$email's Slack account is already deactivated — nothing to do")
        return [pscustomobject]@{ System = 'slack'; Status = 'ok'; Email = $email; Actions = $actions.ToArray() }
    }

    $id = Get-CtgProp $existing 'id'
    Invoke-CtgSlackScim -Method DELETE -Path "/Users/$id" | Out-Null
    $actions.Add("deactivated $email's Slack account (id $id) — messages and files are retained, and it can be reactivated")
    [pscustomobject]@{ System = 'slack'; Status = 'ok'; Email = $email; Actions = $actions.ToArray() }
}

function Confirm-CtgSlack {
    <#
    .SYNOPSIS
        Verify the lane actually did what it claimed — read the account back from Slack.
    #>
    param(
        [Parameter(Mandatory)][pscustomobject]$User,
        [Parameter(Mandatory)][pscustomobject]$Config,
        [Parameter(Mandatory)][ValidateSet('onboard', 'offboard')][string]$Action
    )
    # Same StrictMode-safe chain as the executor — the validator MUST resolve the SAME user, and an
    # offboard payload may carry no UserPrincipalName property at all. Unresolvable is NOT a pass: with
    # no email the lookup below finds nobody, which the offboard branch reads as "never had Slack" and
    # would rubber-stamp a deactivation that nobody performed.
    $email  = [string](@('UserPrincipalName', 'email', 'WorkEmail', 'userToOffboard') | ForEach-Object { Get-CtgProp $User $_ } | Where-Object { $_ -match '@' } | Select-Object -First 1)
    if (-not $email) { return [pscustomobject]@{ ok = $false; checks = @(@{ name = 'no email/UPN on the case to verify against'; expected = $true; actual = $false; pass = $false }) } }
    $u      = Find-CtgSlackUser -Email $email
    $active = if ($u) { Test-CtgSlackActive $u } else { $false }

    $checks = if ($Action -eq 'onboard') {
        @(@{ name = 'slack account active'; pass = [bool]$active; detail = if ($u) { "active=$active" } else { 'no Slack account found' } })
    } else {
        # Offboard passes when the account is gone OR switched off. "Never had Slack" is a pass:
        # there is nothing to contain, and calling it a failure would just block the offboard.
        @(@{ name = 'slack account deactivated'; pass = (-not $active); detail = if (-not $u) { 'no Slack account (nothing to deactivate)' } else { "active=$active" } })
    }
    [pscustomobject]@{ ok = (@($checks | Where-Object { -not $_.pass }).Count -eq 0); checks = $checks }
}

# -------------------------------------------------------------------------------------------------
# BROWSER AUTO-SETUP (sign in + BEST-EFFORT harvest the SCIM token) — LIVE-VALIDATION PENDING
# -------------------------------------------------------------------------------------------------
# DISTINCT from the 'slack' SCIM API token itself: this drives the Slack **console** with a
# 'slack-console' admin login (email + password, optional TOTP) to prove the login and BEST-EFFORT
# locate a SCIM token. Mirrors Coretelligent.Zoom's console setup. A value is never logged.
#
# CAVEAT: a Slack SCIM token is generally NOT exposed as a readable console field (it comes from an app
# install with the admin scope), so the harvest usually returns nothing — that is EXPECTED, and the
# operator pastes the token via the guided form instead. This never fabricates a token.

# Read a field off a brokered secret by any of its synonyms (case/space-insensitive). The secret is
# either a pscustomobject or a hashtable, with the fields on the object or under a .Fields member.
function Get-CtgSlackConsoleField {
    param($Secret, [string[]]$Names)
    if (-not $Secret) { return $null }
    $bag = $Secret
    $fields = Get-CtgProp $Secret 'Fields'
    if ($fields) { $bag = $fields }
    foreach ($n in $Names) {
        $v = Get-CtgProp $bag $n
        if ($null -ne $v -and "$v".Trim() -ne '') { return [string]$v }
    }
    return $null
}

function Resolve-CtgSlackConsoleLogin {
    param($Secret)
    $email = Get-CtgSlackConsoleField $Secret @('Username', 'Email', 'User', 'Login', 'AdminEmail', 'Admin Email')
    $password = Get-CtgSlackConsoleField $Secret @('Password', 'Pass', 'Secret')
    if ([string]::IsNullOrWhiteSpace($email) -or $email -notmatch '@') {
        return [pscustomobject]@{ Ok = $false; Reason = "no 'slack-console' admin login wired (an email + password) — the Username must be an admin email, not a SCIM token." }
    }
    if ([string]::IsNullOrWhiteSpace($password)) {
        return [pscustomobject]@{ Ok = $false; Reason = "the 'slack-console' secret has no Password." }
    }
    [pscustomobject]@{ Ok = $true; Username = $email; Password = $password }
}

function Invoke-CtgSlackConsoleSetup {
    <#
    .SYNOPSIS
        Drive Slack via the browser sidecar. Config.signInOnly=$true: SIGN-IN TEST (prove the console
        login works; change nothing). signInOnly=$false: additionally BEST-EFFORT locate + harvest a
        SCIM token and return it as a `Credentials` note-property (never logged) so the APP vaults it.
        Slack SCIM tokens usually are NOT console-harvestable (they come from an app with the admin
        scope) — a "signed in, no token" result is EXPECTED and NOT an error; the operator pastes the
        token instead. Selectors are LIVE-VALIDATION PENDING. THROWS only on a failed flow (bad login).
    #>
    [CmdletBinding()]
    param(
        [AllowNull()][pscustomobject]$Config,
        $Secret,
        [string]$SecretName = 'slack-console'
    )
    $actions = [System.Collections.Generic.List[string]]::new()
    $login = Resolve-CtgSlackConsoleLogin -Secret $Secret
    if (-not $login.Ok) { throw "Slack console sign-in could not start — $($login.Reason)" }

    $signInOnlyProp = Get-CtgProp $Config 'signInOnly'
    $signInOnly = ($null -eq $signInOnlyProp) -or [bool]$signInOnlyProp
    $params = @{ signInOnly = $signInOnly }
    $consoleUrl = [string](Get-CtgProp $Config 'consoleUrl'); if (-not [string]::IsNullOrWhiteSpace($consoleUrl)) { $params['consoleUrl'] = $consoleUrl }
    $workspace = [string](Get-CtgProp $Config 'workspace'); if (-not [string]::IsNullOrWhiteSpace($workspace)) { $params['workspace'] = $workspace }
    $totpSeed = Get-CtgSlackConsoleField $Secret @('TOTPSeed', 'TOTP Seed', 'TOTP', 'OTPSeed', 'MFASeed', 'AuthenticatorSeed', 'otpauth')
    if ($totpSeed) { $params['otp'] = @{ totpSeed = $totpSeed }; $actions.Add("WARN using a stored TOTP seed — prefer enabling One-Time Password on the Delinea secret") }

    $flowInput = @{ username = $login.Username; password = $login.Password; params = $params }
    $res = Invoke-CtgBrowserFlow -Flow 'slack-console-setup' -InputObject $flowInput -TimeoutSeconds 300
    if ($res.ok) {
        $actions.Add($(if ($res.message) { $res.message } else { 'signed in to Slack' }))
        $out = [pscustomobject]@{ System = 'slack-console-setup'; Status = 'ok'; Actions = $actions.ToArray() }
        if ($res.harvested -and $res.harvested.token) {
            Add-Member -InputObject $out -NotePropertyName Credentials -NotePropertyValue ([pscustomobject]@{ token = [string]$res.harvested.token })
        }
        return $out
    }
    $err = if ($res.error) { $res.error } else { 'unknown error' }
    $ex = [System.Exception]::new("Slack console setup failed: $err")
    if ($res.evidence) { $ex.Data['Evidence'] = [string]$res.evidence }
    throw $ex
}

Export-ModuleMember -Function Connect-CtgSlack, Invoke-CtgSlackScim, Test-CtgSlackNoScim, Find-CtgSlackUser, Test-CtgSlackActive, Invoke-CtgSlackOnboarding, Invoke-CtgSlackOffboarding, Confirm-CtgSlack, Resolve-CtgSlackConsoleLogin, Invoke-CtgSlackConsoleSetup
