import type { ChangelogEntry } from "../format";

export const entry: ChangelogEntry = {
  id: "azure-inventory-and-s1-roster",
  date: "2026-07-17",
  time: "07:45",
  title: "Azure migration inventory committed (script reviewed + fixed) and SentinelOne unwire roster preserved",
  items: [
    "The Azure migration inventory script is now in the repo, reviewed and fixed: one shared pruned file walk (node_modules, .git, .claude and .next excluded everywhere - the old per-section copies drifted and let vendored files flood the report), and paths are passed to Python as arguments instead of being spliced into the code",
    "The inventory report was regenerated by the fixed script - the old copy wrongly reported the repo as containing a FastAPI service (the search matched its own command line) and listed Claude worktree internals as project files",
    "Security review fix: the committed report now honors .gitignore - the first cut enumerated the full generated client roster (254 real client names) and the client KB corpus, both fenced off as keep-local; the script filters through git check-ignore so gitignored paths never reach a committed report (1441 lines down to 464)",
    "The SentinelOne unwire roster (40 clients mapped to their Delinea secret IDs and folder paths, no secret values) is preserved in the repo as the record of the 2026-07-13 unwire pass",
    "Known quirks in that roster are documented, not edited, because they mirror Secret Server reality: MarketScience appears twice (one row with a blank CORE id) and two secret names carry trailing spaces (Coastal Bridge, JAT) - always match on the secret ID, never the name",
  ],
};
