import type { ChangelogEntry } from "../format";

export const entry: ChangelogEntry = {
  id: "m365-password-reset-permission",
  date: "2026-07-16",
  time: "17:00",
  title: "Microsoft 365 password resets: name the permission Graph actually needs, and stop asking admins for domain write access",
  items: [
    "Every Microsoft 365 password reset in the fleet has been failing with a bare '[Authorization_RequestDenied] Insufficient privileges', on credentials whose connection test was green (UM0028954/Emporia Software hit this on an onboard). A sweep of all 76 clients confirms it was never client-specific: 0 of the 31 wired tenants could reset a cloud password",
    "Cause: Microsoft Graph gates changing a password behind its own permission, User-PasswordProfile.ReadWrite.All. We never asked for it - not in the connection test, not in the fleet audit, not on the setup page we hand clients. So the test reported 'all required permissions present' about a tenant that provably could not reset a password",
    "This is also why a case could get its account step right and then fail on the very next step with the same credential: User.ReadWrite.All covers setting a password while CREATING an account, but not changing one afterwards - and only a reset changes one. UM0028954 hit it the common way: the onboard ADOPTED an existing account (which deliberately leaves the password alone), so the operator clicked 'Generate random password' to set a known one, and that was the call Graph refused",
    "Two related fixes so the advice actually works. The runner connects to Graph once per tenant and reuses the token, so a reset attempted after the permission is granted was still denied by a token minted before the consent - and the automatic token-refresh that exists for exactly this only covered the m365 and entra steps, not the reset (nor TAP or notify). It now covers every step that shares the Graph session, so granting the permission is enough. Separately, the reset now retries a throttled or gateway-blipped write like every other Graph write does: because the one-time password is wiped after it is shown, a reset lost to a blip could not be re-run at all",
    "The connection test and fleet audit now check the permission and show a miss as '(optional)', not a red failure - a client who never resets a cloud password is unaffected, and making it required would fail every test in the fleet today. The setup page at /help/cloud-auth now lists it, and the runner's error names it, explains why the account step succeeded, and says what to do",
    "Fixed while we were here: the setup page told admins to grant Domain.Read.All using an id that was actually Domain.ReadWrite.All - asking clients for permission to WRITE their tenant's domains to satisfy a read-only need. Every id we hand out is now read back from Microsoft's own Graph service principal and pinned by a test; `npx tsx scripts/verify-graph-role-ids.ts` re-checks them against Microsoft on demand",
    "We then audited every Graph call the runner makes against the permission list, because 'a feature shipped and nobody asked for its permission' turned out to be a pattern rather than a one-off. Two more: sending an offboard notification needs Mail.Send (no client has it), and disabling a leaver's Entra devices needs Device.ReadWrite.All (only our own tenant has it). Both are now checked and shown as optional; both affect one configured client today",
    "Also fixed a permission we were asking for and did not need: a tenant with Directory.Read.All can already read its verified domains, but the test still told it to grant Domain.Read.All. The setup page's permission list is now generated from the same table the test and the audit use, so the page can no longer drift from what the runner actually calls - which is how the password-reset role went unasked-for in the first place",
    "Grant it in Entra -> App registrations -> API permissions -> Microsoft Graph -> Application permissions -> User-PasswordProfile.ReadWrite.All, then Grant admin consent. A token minted before the consent keeps the old permissions, but the runner now refreshes it by itself, so granting is enough",
    "New, and the reverse question: the connection test and the fleet audit now also report what an app registration holds that we never use. Being over-permissioned never fails a test - a permission we don't use isn't a fault in our setup, and the app registration may be shared with tooling that isn't ours - but you can now see it, and it names what each role actually permits rather than just listing it",
    "It found more than expected. Five clients' credentials can add credentials to ANY app registration in their tenant (Application.ReadWrite.All), and four can assign directory roles - which means making themselves Global Administrator (RoleManagement.ReadWrite.Directory). Two hold full access to every mailbox in the tenant. Three of those clients are simultaneously MISSING permissions they need: they cannot create a user, but they could make themselves a tenant admin. Worth raising with each client - removing one is their call, not ours",
    "Agents pick this up on runner 1.68.0",
  ],
};
